cuisines/urls.py
from django.conf.urls import url

from . import views

app_name = 'cuisines'

urlpatterns = [
    url(r"^$", views.ListCuisines.as_view(), name="all"),
    url(r"^new/$", views.CreateNewCuisine.as_view(), name="create"),
    url(r"^recipes/in/(?P<slug>[-\w]+)/$",views.SingleCuisine.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinCuisine.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveCuisine.as_view(),name="leave"),
]

foodnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^login_redirect/$", views.LoginPage.as_view(), name="login_redirect"),
    url(r"^logout_redirect/$", views.LogoutPage.as_view(), name="logout_redirect"),
    url(r"^admin/", admin.site.urls),
    url(r"^useraccounts/", include("useraccounts.urls", namespace="useraccounts")),
    url(r"^usersaccounts/", include("django.contrib.auth.urls")),
    url(r"^recipes/", include("recipes.urls", namespace="recipes")),
    url(r"^cuisines/",include("cuisines.urls", namespace="cuisines")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.conf.urls import url
from . import views

app_name='recipes'

urlpatterns = [
    url(r"^$", views.RecipeList.as_view(), name="all"),
    url(r"new/$", views.CreateRecipe.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserRecipes.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.RecipeDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteRecipe.as_view(),name="delete"),
    url(r"upvote/(?P<pk>\d+)/$",views.UpvoteRecipe,name="upvote"),
    url(r"update/(?P<pk>\d+)/$",views.UpdateRecipe.as_view(),name="update"),
]

cuisines/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()


class Cuisine(models.Model):

    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="CuisineMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
 
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("cuisines:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class CuisineMember(models.Model):
    cuisine = models.ForeignKey(Cuisine, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_cuisines', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("cuisine", "user")

cuisines/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from cuisines.models import Cuisine, CuisineMember
from . import models

class CreateNewCuisine(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Cuisine

class SingleCuisine(generic.DetailView):
    model = Cuisine

class ListCuisines(generic.ListView):
    model = Cuisine


class JoinCuisine(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("cuisines:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        cuisine = get_object_or_404(Cuisine,slug=self.kwargs.get("slug"))

        try:
            CuisineMember.objects.create(user=self.request.user,cuisine=cuisine)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(cuisine.name)))

        else:
            messages.success(self.request,"You are now a member of the {} cuisine.".format(cuisine.name))

        return super().get(request, *args, **kwargs)


class LeaveCuisine(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("cuisines:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:
            membership = models.CuisineMember.objects.filter(
                user=self.request.user,
                cuisine__slug=self.kwargs.get("slug")
            ).get()

        except models.CuisineMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this cuisine because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this cuisine."
            )
        return super().get(request, *args, **kwargs)

cuisines/templates/cuisines/cuisine_base.html
{% extends "base.html" %}
{% block content %}
{% block cuisinecontent %}
{% endblock %}

{% endblock %}

cuisines/templates/cuisines/cuisine_detail.html
{% extends "cuisines/cuisine_base.html" %}

{% block cuisinecontent %}
<div class = "container">

	<!-- If user is not a member of a cuisine give him the option to join, else to leave -->
	<div class="row justify-content-end">
		<div class="col-2"><h1><font size="7" color="red">{{cuisine.name}}</font></h1></div>
		<div class="col-2">
			{% if user in cuisine.members.all %}
			<a href="{% url 'cuisines:leave' slug=cuisine.slug %}" class="btn btn-lg btn-fill btn-warning"> Leave </a>
			{% else %}
			<a href="{% url 'cuisines:join' slug=cuisine.slug %}" class="btn btn-lg btn-fill btn-warning"> Join </a>
			{% endif %}
		</div>
	</div>

	<br/>

	{% if cuisine.recipes.count == 0 %}
	<h2>No recipes in this cuisine yet!</h2>
	{% else %}
	{% for recipe in cuisine.recipes.all %}
	<div class="row justify-content-center"><h1> <font color="green"> {{ recipe.dish_title }} </font></h1></div>
	<div class="row justify-content-center"><img src="{{ recipe.dish_image.url }}" height=400 width=400/></div>

	<br/>
	<div class="row justify-content-start"> 
		<h5> Cooking Time: {{ recipe.cooking_time }}</h5>
		<p>{{ recipe.method }}</p> 
		<p>
			<a href="{% url 'recipes:for_user' username=recipe.user.username %}">@{{ recipe.user.username }}</a>
			<time class="time"><a href="{% url 'recipes:single' username=recipe.user.username pk=recipe.pk %}">{{ recipe.created_at }}</a></time>
		</p>
	</div>

	<br/>
	<div class="d-flex">
		<!-- Allow deletion and updates only if it is by the same user that created the recipe -->
		{% if user.is_authenticated and recipe.user == user and not hide_delete %}
		<div class="p-1"><a href="{% url 'recipes:update' pk=recipe.pk %}"><button class="btn btn-primary btn-lg"> Update </button></a></div>
		<div class="p-1"><a href="{% url 'recipes:delete' pk=recipe.pk %}" title="delete" class="btn btn-danger btn-lg"> <span class="oi oi-delete"></span> Delete</a></div>
		{% endif %}
		<div class="ml-auto p-2"><a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-success btn-lg"><span class="oi oi-caret-top"></span> Upvote {{ recipe.votes_total }}</button></a></div>
	</div>

	<form id="upvote" method="POST" action="{% url 'recipes:upvote' pk=recipe.pk %}">
		{% csrf_token%}
		<input type="hidden">
	</form>
	</br>
	{% endfor %}
	{% endif %}
</div>
{% endblock %}

cuisines/templates/cuisines/cuisine_form.html
{% extends "cuisines/cuisine_base.html" %}
{% load bootstrap4 %}

{% block cuisinecontent %}
<div class="container">
	<h4>Create A New Cuisine</h4>
	<form method="POST" action="{% url 'cuisines:create' %}" id="cuisineForm">
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" value="Create" class="btn btn-primary btn-large">
	</form>
</div>
{% endblock %}

cuisines/templates/cuisines/cuisine_list.html
{% extends "cuisines/cuisine_base.html" %}

{% block cuisinecontent %}
<div class="row">
	<div class="col-md-4">
		<div class="content">
			{% if user.is_authenticated %}
			<h2>
				Welcome back
				<a href="{% url 'recipes:for_user' username=user.username %}">@{{user.username }}</a> 
			</h2>
			{% endif %}
			<p>Welcome to the Cuisines Page! Select a Cuisine with a shared interest!</p>
		</div>
		{% if user.is_authenticated %}
		<a href="{% url 'cuisines:create' %}" class="btn btn-md btn-fill btn-warning">Create New Cuisine!</a>
		{% endif %}
	</div>

	<div class="col-md-8">
		<div class="list-group">
			{% for cuisine in object_list %}
			<a class="list-group-item" href="{% url 'cuisines:single' slug=cuisine.slug %}">
				<h3>{{ cuisine.name }}</h3>
				<div class="container-fluid">
					{{ cuisine.description_html|safe }}
					<div class="row">
						<div class="col-md-4">
							<span class="badge">{{ cuisine.members.count }}</span> member{{ cuisine.members.count|pluralize }}
						</div>
						<div class="col-md-4">
							<span class="badge">{{ cuisine.recipes.count }}</span> recipe{{ cuisine.recipes.count|pluralize }}
						</div>
					</div>
				</div>
			</a>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}