foodnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^login_redirect/$", views.LoginPage.as_view(), name="login_redirect"),
    url(r"^logout_redirect/$", views.LogoutPage.as_view(), name="logout_redirect"),
    url(r"^admin/", admin.site.urls),
    url(r"^useraccounts/", include("useraccounts.urls", namespace="useraccounts")),
    url(r"^usersaccounts/", include("django.contrib.auth.urls")),
    url(r"^recipes/", include("recipes.urls", namespace="recipes")),
    url(r"^cuisines/",include("cuisines.urls", namespace="cuisines")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.conf.urls import url
from . import views

app_name='recipes'

urlpatterns = [
    url(r"^$", views.RecipeList.as_view(), name="all"),
    url(r"new/$", views.CreateRecipe.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserRecipes.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.RecipeDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteRecipe.as_view(),name="delete"),
    url(r"upvote/(?P<pk>\d+)/$",views.UpvoteRecipe,name="upvote"),
    url(r"update/(?P<pk>\d+)/$",views.UpdateRecipe.as_view(),name="update"),
]

recipes/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

import misaka

from cuisines.models import Cuisine

from django.contrib.auth import get_user_model
User = get_user_model()


class Recipe(models.Model):
    user = models.ForeignKey(User, related_name="recipes", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    dish_title = models.CharField(max_length=255)
    dish_image = models.FileField(upload_to='images/')
    cooking_time = models.CharField(max_length=50)
    method = models.TextField()
    method_html = models.TextField(editable=False)
    votes_total = models.IntegerField(default=1)
    cuisine = models.ForeignKey(Cuisine, related_name="recipes",null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.method

    def save(self, *args, **kwargs):
        self.method_html = misaka.html(self.method)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "recipes:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "method"]

recipes/forms.py
from django import forms
from recipes import models


class RecipeForm(forms.ModelForm):
    class Meta:
        fields = ("dish_title", "dish_image", "cooking_time", "method", "cuisine")
        model = models.Recipe

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["cuisine"].queryset = (
                models.Cuisine.objects.filter(
                    pk__in=user.cuisines.values_list("cuisine__pk")
                )
            )

recipes/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from .models import Recipe
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class RecipeList(SelectRelatedMixin, generic.ListView):
    model = models.Recipe
    select_related = ("user", "cuisine")


class UserRecipes(generic.ListView):
    model = models.Recipe
    template_name = "recipes/user_recipe_list.html"

    def get_queryset(self):
        try:
            self.recipe_user = User.objects.prefetch_related("recipes").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.recipe_user.recipes.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipe_user"] = self.recipe_user
        return context


class RecipeDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Recipe
    select_related = ("user", "cuisine")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

class CreateRecipe(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('dish_title', 'dish_image', 'cooking_time', 'method', 'cuisine')
    model = models.Recipe

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user 
        self.object.save()
        return super().form_valid(form)

class UpdateRecipe(LoginRequiredMixin, SelectRelatedMixin, generic.UpdateView):
    fields = ('dish_title', 'dish_image', 'cooking_time', 'method')
    model = models.Recipe
    select_related = ("user", "cuisine")
    template_name = "recipes/recipe_update_form.html"

class DeleteRecipe(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Recipe
    select_related = ("user", "cuisine")
    success_url = reverse_lazy("recipes:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Recipe Deleted")
        return super().delete(*args, **kwargs)

def UpvoteRecipe(request, pk):
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, pk=pk)
        recipe.votes_total += 1
        recipe.save()
        return redirect('/recipes/by/' +  str(request.user.username) + '/' + str(pk))

recipes/templates/recipes/_recipe.html
<div class="container">
	<h1>{{ recipe.dish_title }} </h1>
	<img class="img-fluid" src="{{ recipe.dish_image.url }}" height=300 width=300/>
	<h5>{{ recipe.cooking_time }}</h5>
	<p>{{ recipe.method }}</p>
	<p>
		<span class="username"><a href="{% url 'recipes:for_user' username=recipe.user.username %}">@{{ recipe.user.username }}</a></span>

		<time class="time"><a href="{% url 'recipes:single' username=recipe.user.username pk=recipe.pk %}">{{ recipe.created_at }}</a></time>

		
		<a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-primary btn-lg"><span class="oi oi-caret-top"></span> Upvote {{ recipe.votes_total }}</button></a>
	</p>
	
	<form id="upvote" method="POST" action="{% url 'recipes:upvote' pk=recipe.pk %}">
		{% csrf_token%}
		<input type="hidden">
	</form>

	<!-- Only if it is the same user that posted the recipe allow them to update and delete the recipe -->
	{% if user.is_authenticated and recipe.user == user and not hide_delete %}
		<a href="{% url 'recipes:update' pk=recipe.pk %}"><button class="btn btn-primary btn-lg">Update </button></a>
		<a href="{% url 'recipes:delete' pk=recipe.pk %}" title="delete"><button class="btn btn-danger btn-lg">Delete</a>
	{% endif %}
</div>

recipes/templates/recipes/recipe_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	{% block recipe %}
	{% endblock %}
</div>
{% endblock %}

recipes/templates/recipes/recipe_confirm_delete.html
{% extends "recipes/recipe_base.html" %}


{% block recipe %}
<div class="row justify-content-start"> <h1> <font color="red"> Are you sure you want to delete this recipe? </font> </h1> </div>
<div class="row justify-content-start"><h2> <font color="green"> {{ recipe.dish_title }} </font></h2> <</div>
<div class="row justify-content-start"><img src="{{ recipe.dish_image.url }}" height=400 width=400/></div>

<br/>
<div class="row justify-content-start"> 
	<h5> Cooking Time: {{ recipe.cooking_time }}</h5>
	<p>{{ recipe.method }}</p> 
	<p>
		<a href="{% url 'recipes:for_user' username=recipe.user.username %}">@{{ recipe.user.username }}</a>
		<time class="time"><a href="{% url 'recipes:single' username=recipe.user.username pk=recipe.pk %}">{{ recipe.created_at }}</a></time>
	</p>
</div>
</br>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'recipes:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends "recipes/recipe_base.html" %}

{% block recipe %}
<div class="row justify-content-center"><h1>{{ recipe.dish_title }}</h1><</div>
<div class="row justify-content-center"><img src="{{ recipe.dish_image.url }}" height=400 width=400/></div>

<br/>
<div class="row justify-content-start"> 
<h5> Cooking Time: {{ recipe.cooking_time }}</h5>
<p>{{ recipe.method }}</p> </div>
<p>
	<a href="{% url 'recipes:for_user' username=recipe.user.username %}">@{{ recipe.user.username }}</a>
	<time class="time"><a href="{% url 'recipes:single' username=recipe.user.username pk=recipe.pk %}">{{ recipe.created_at }}</a></time>
</p>
</div>

<br/>
<div class="d-flex">
	{% if user.is_authenticated and recipe.user == user and not hide_delete %}
		<div class="p-2"><a href="{% url 'recipes:update' pk=recipe.pk %}"><button class="btn btn-primary btn-lg"> Update </button></a></div>
		<div class="p-2"><a href="{% url 'recipes:delete' pk=recipe.pk %}" title="delete" class="btn btn-danger btn-lg"> <span class="oi oi-delete"></span> Delete</a></div>
	{% endif %}
	<div class="ml-auto p-2"><a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-success btn-lg"><span class="oi oi-caret-top"></span> Upvote {{ recipe.votes_total }}</button></a></div>
</div>

<form id="upvote" method="POST" action="{% url 'recipes:upvote' pk=recipe.pk %}">
	{% csrf_token%}
	<input type="hidden">
</form>
{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends "recipes/recipe_base.html" %}

{% load bootstrap4 %}

{% block recipe %}
<h4>Create New Recipe</h4>
<form method="POST" action="{% url 'recipes:create' %}" id="recipeForm" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Create Recipe" class="btn btn-primary btn-large">
</form>

{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends "recipes/recipe_base.html" %}
{% load humanize %}

{% block recipe %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Cuisines</h5>
			<ul class="list-unstyled">
				{% for member_cuisine in get_user_cuisines %}
				<li class="group li-with-bullet">
					<a href="{% url 'cuisines:single' slug=member_cuisine.cuisine.slug %}">{{ member_cuisine.cuisine.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Cuisines</h5>
			<ul class="list-unstyled">
				{% for other_cuisine in get_other_cuisines %}
					<li class="group li-with-bullet"><a href="{% url 'cuisines:single' slug=other_cuisine.slug %}">{{ other_cuisine.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

<div class="col-md-8">
	{% for recipe in recipe_list %}
  		{% include "recipes/_recipe.html" %}
	{% endfor %}
</div>
{% endblock %}

recipes/templates/recipes/recipe_update_form.html
{% extends "recipes/recipe_base.html" %}

{% load bootstrap4 %}

{% block recipe %}
<h4>Update Recipe</h4>
<form method="POST" action="{% url 'recipes:update' pk=recipe.pk%}" id="recipeForm" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Update Recipe" class="btn btn-primary btn-large">
</form>

{% endblock %}

recipes/templates/recipes/user_recipe_list.html
{% extends "recipes/recipe_base.html" %}
{% block recipe %}

<div class="row justify-content-end"><h3>@{{ recipe_user.username }}</h3></div>
<ul class="list-group">
{% for recipe in recipe_list %}
<li class="list-group-item">
	<div class="row justify-content-center"><h1><font color="green">  {{ recipe.dish_title }} </font></h1><</div>
	<div class="row justify-content-center"><img src="{{ recipe.dish_image.url }}" height=400 width=400/></div>
	<div class="row justify-content-start"> 
		<h5> Cooking Time: {{ recipe.cooking_time }}</h5>
		<p>{{ recipe.method }}</p> 
		<p>
			<a href="{% url 'recipes:for_user' username=recipe.user.username %}">@{{ recipe.user.username }}</a>
			<time class="time"><a href="{% url 'recipes:single' username=recipe.user.username pk=recipe.pk %}">{{ recipe.created_at }}</a></time>
		</p>
	</div>

	<br/>

	<div class="d-flex">
		{% if user.is_authenticated and recipe.user == user and not hide_delete %}
			<div class="p-2"><a href="{% url 'recipes:update' pk=recipe.pk %}"><button class="btn btn-primary btn-lg"> Update </button></a></div>
			<div class="p-2"><a href="{% url 'recipes:delete' pk=recipe.pk %}" title="delete" class="btn btn-danger btn-lg"> <span class="oi oi-delete"></span> Delete</a></div>
		{% endif %}
		<div class="ml-auto p-2"><a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-success btn-lg"><span class="oi oi-caret-top"></span> Upvote {{ recipe.votes_total }}</button></a></div>
	</div>

	<form id="upvote" method="POST" action="{% url 'recipes:upvote' pk=recipe.pk %}">
		{% csrf_token%}
		<input type="hidden">
	</form>
</li>
{% endfor %}
</ul>
{% endblock %}