foodnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^login_redirect/$", views.LoginPage.as_view(), name="login_redirect"),
    url(r"^logout_redirect/$", views.LogoutPage.as_view(), name="logout_redirect"),
    url(r"^admin/", admin.site.urls),
    url(r"^useraccounts/", include("useraccounts.urls", namespace="useraccounts")),
    url(r"^usersaccounts/", include("django.contrib.auth.urls")),
    url(r"^recipes/", include("recipes.urls", namespace="recipes")),
    url(r"^cuisines/",include("cuisines.urls", namespace="cuisines")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.conf.urls import url
from . import views

app_name='recipes'

urlpatterns = [
    url(r"^$", views.RecipeList.as_view(), name="all"),
    url(r"new/$", views.CreateRecipe.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserRecipes.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.RecipeDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteRecipe.as_view(),name="delete"),
    url(r"upvote/(?P<pk>\d+)/$",views.UpvoteRecipe,name="upvote"),
    url(r"update/(?P<pk>\d+)/$",views.UpdateRecipe.as_view(),name="update"),
]

useraccounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'useraccounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

templates/base.html
    <!DOCTYPE html>
    {% load staticfiles %}
    <html>
      <head>
        <meta charset="utf-8">

        <title>Food Net</title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'foodnet/master.css'%}">
        <link href="{% static 'open-iconic-master/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">

      </head>

      <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    		  <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
              <img src="{% static 'logo.png' %}" height=35 width=35 class="d-inline-block alighn-top"/> Food Net</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                      <li><a href="{% url 'recipes:create' %}" class="btn btn-simple">Add Recipe</a></li>
                      <li><a href="{% url 'cuisines:create' %}" class="btn btn-simple">Add Cuisine</a></li>
                      <li><a href="{% url 'cuisines:all' %}" class="btn btn-simple">All Cuisines</a></li>
                      <li><a href="{% url 'useraccounts:logout' %}" class="btn btn-simple">Log out</a></li>
                {% else %}
                      <li><a href="{% url 'cuisines:all' %}"class="btn btn-simple">Cuisines</a></li>
                      <li><a href="{% url 'useraccounts:login' %}" class="btn btn-simple">Log in</a></li>
                      <li><a href="{% url 'useraccounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                {% endif %}
              </ul>  
            </div>
            </div>
    			</div>
    		</nav>
        <br/>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}
        </div>
      </body>
    </html>

templates/index.html
{% extends "base.html" %}
{% block content %}
	<h1>Welcome to Food Net!</h1>
	<h2>The online user community for Chefs!</h2>
	<h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

templates/login_redirect.html
{% extends "base.html" %}
{% block content %}
<section class="jumbotron text-center">
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'cuisines:all'%}">Go to Cuisines</a></h2>
</div>
</section>
{% endblock %}

templates/logout_redirect.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}